//! Codegen tests driven by JSON introspection fixtures — no real database.

use serde_json::{Map, Value};

use miiigrate::codegen::{
    emit_typescript, pascal_case, pg_ir_from_rows, pg_type_to_ts, sqlite_ir_from_rows,
    sqlite_type_to_ts, EnumIr,
};

fn rows(json: &str) -> Vec<Map<String, Value>> {
    serde_json::from_str(json).unwrap()
}

#[test]
fn pg_fixture_produces_expected_ir() {
    let columns = rows(include_str!("fixtures/pg_columns.json"));
    let enums = rows(include_str!("fixtures/pg_enums.json"));
    let ir = pg_ir_from_rows(&columns, &enums).unwrap();

    // Tracking table excluded; fixture order (alphabetical) preserved.
    let names: Vec<_> = ir.tables.iter().map(|t| t.name.as_str()).collect();
    assert_eq!(names, ["orders", "users"]);

    let orders = &ir.tables[0];
    let by_name = |n: &str| {
        orders
            .columns
            .iter()
            .find(|c| c.name == n)
            .unwrap_or_else(|| panic!("column {n}"))
    };
    assert_eq!(by_name("id").ts_type, "string"); // int8
    assert!(!by_name("id").nullable);
    assert_eq!(by_name("user_id").ts_type, "number");
    assert_eq!(by_name("amount").ts_type, "string"); // numeric
    assert_eq!(by_name("mood").ts_type, "Mood"); // enum
    assert!(by_name("mood").nullable);
    assert_eq!(by_name("tags").ts_type, "string[]"); // _text array
    assert_eq!(by_name("metadata").ts_type, "Json"); // jsonb
    assert_eq!(by_name("created_at").ts_type, "Date | string");

    assert_eq!(ir.enums.len(), 2);
    assert_eq!(ir.enums[0].name, "mood");
    assert_eq!(ir.enums[0].labels, ["happy", "sad"]);
}

#[test]
fn pg_fixture_emits_expected_typescript() {
    let columns = rows(include_str!("fixtures/pg_columns.json"));
    let enums = rows(include_str!("fixtures/pg_enums.json"));
    let ir = pg_ir_from_rows(&columns, &enums).unwrap();
    let ts = emit_typescript(&ir, "postgres");

    assert!(ts.starts_with("/**\n * generated by miiigrate, do not edit."));
    assert!(ts.contains("export type Json ="));
    assert!(ts.contains("export type Mood = 'happy' | 'sad';"));
    // Enum label with a quote is escaped.
    assert!(ts.contains("export type OrderStatus = 'pending' | 'shipped' | 'it\\'s done';"));
    assert!(ts.contains("export interface Orders {"));
    assert!(ts.contains("  amount: string;"));
    assert!(ts.contains("  mood: Mood | null;"));
    assert!(ts.contains("  tags: string[] | null;"));
    assert!(ts.contains("  metadata: Json | null;"));
    assert!(ts.contains("  created_at: Date | string;"));
    assert!(ts.contains("  birth_date: Date | string | null;"));
    assert!(ts.contains("  avatar: Buffer | null;"));
    // Property with invalid identifier chars is quoted.
    assert!(ts.contains("  'weird-col name': string | null;"));
    // Aggregate type references raw table names.
    assert!(ts.contains("export interface Database {"));
    assert!(ts.contains("  orders: Orders;"));
    assert!(ts.contains("  users: Users;"));
    // Tracking table stays out.
    assert!(!ts.contains("IiiMigrations"));
}

#[test]
fn sqlite_fixture_produces_expected_typescript() {
    let fixture: serde_json::Map<String, Value> =
        serde_json::from_str(include_str!("fixtures/sqlite_tables.json")).unwrap();
    let tables: Vec<(String, Vec<Map<String, Value>>)> = fixture
        .into_iter()
        .map(|(name, rows)| {
            let rows = rows
                .as_array()
                .unwrap()
                .iter()
                .map(|r| r.as_object().unwrap().clone())
                .collect();
            (name, rows)
        })
        .collect();

    let ir = sqlite_ir_from_rows(&tables).unwrap();
    assert_eq!(ir.tables.len(), 1, "tracking table excluded");
    let ts = emit_typescript(&ir, "sqlite");

    assert!(ts.contains("export interface Users {"));
    assert!(ts.contains("  id: number;")); // pk INTEGER: non-null
    assert!(ts.contains("  name: string;"));
    assert!(ts.contains("  email: string | null;"));
    assert!(ts.contains("  score: number | null;"));
    assert!(ts.contains("  avatar: Buffer | null;"));
    assert!(ts.contains("  is_admin: boolean;"));
    assert!(ts.contains("  created_at: string;")); // DATETIME affinity
    assert!(ts.contains("  users: Users;"));
}

#[test]
fn pg_type_mapping_table() {
    let enums = vec![EnumIr {
        name: "mood".into(),
        labels: vec!["happy".into()],
    }];
    for (data_type, udt, expected) in [
        ("smallint", "int2", "number"),
        ("integer", "int4", "number"),
        ("bigint", "int8", "string"),
        ("numeric", "numeric", "string"),
        ("real", "float4", "number"),
        ("double precision", "float8", "number"),
        ("boolean", "bool", "boolean"),
        ("text", "text", "string"),
        ("character varying", "varchar", "string"),
        ("uuid", "uuid", "string"),
        ("date", "date", "Date | string"),
        ("timestamp with time zone", "timestamptz", "Date | string"),
        ("timestamp without time zone", "timestamp", "Date | string"),
        ("json", "json", "Json"),
        ("jsonb", "jsonb", "Json"),
        ("bytea", "bytea", "Buffer"),
        ("interval", "interval", "string"),
        ("USER-DEFINED", "mood", "Mood"),
        ("USER-DEFINED", "some_extension_type", "unknown"),
        ("ARRAY", "_int4", "number[]"),
        ("ARRAY", "_mood", "Mood[]"),
    ] {
        assert_eq!(
            pg_type_to_ts(data_type, udt, &enums),
            expected,
            "{data_type}/{udt}"
        );
    }
}

#[test]
fn sqlite_type_mapping_table() {
    for (decl, expected) in [
        ("INTEGER", "number"),
        ("int", "number"),
        ("BIGINT", "number"),
        ("TEXT", "string"),
        ("VARCHAR(80)", "string"),
        ("CLOB", "string"),
        ("BLOB", "Buffer"),
        ("", "Buffer"),
        ("REAL", "number"),
        ("DOUBLE", "number"),
        ("NUMERIC(10,2)", "number"),
        ("BOOLEAN", "boolean"),
        ("DATETIME", "string"),
        ("DATE", "string"),
        ("SOMETHING ODD", "unknown"),
    ] {
        assert_eq!(sqlite_type_to_ts(decl), expected, "{decl}");
    }
}

#[test]
fn pascal_case_conversions() {
    assert_eq!(pascal_case("users"), "Users");
    assert_eq!(pascal_case("order_items"), "OrderItems");
    assert_eq!(pascal_case("order-items"), "OrderItems");
    assert_eq!(pascal_case("_iii_migrations"), "IiiMigrations");
}
